name: ProjectManager
on:
    project_card:
      types: [moved, created]
jobs:
    label_issues:
      #      if: endsWith( "Todo", github.event.project_card.column_url )
      runs-on: ubuntu-latest
      permissions:
        issues: write
      steps:
        - uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["TODO"]
              })
